### ISSUE TITLE
Clarification for the base of the log used

### ISSUE THREAD

**Issue by mcewenkhundi** [petermacp/BlantyreTBEpi#2]
The log transformations used is a nature log

![gitissue](https://user-images.githubusercontent.com/40823168/42410923-89f3d706-81f2-11e8-9d04-bc054f87b31c.JPG)

Yet the labels on the the graph say says its log(10), I might have missed the transformation.
![issue2](https://user-images.githubusercontent.com/40823168/42410940-ea724018-81f2-11e8-9f53-07f4a9225f21.JPG)

**Comment by petermacp** [comment]
@mcewenkhundi  

Fixed in commit 48b22c8
